[cerebrium.deployment]
name = "latentsync"
python_version = "3.11"
disable_auth = false

[cerebrium.hardware]
compute = "AMPERE_A10"
cpu = 8
memory = 32.0

[cerebrium.scaling]
min_replicas = 0
cooldown = 0

[cerebrium.dependencies]

[cerebrium.dependencies.apt]
ffmpeg = "latest"
libgl1 = "latest"

[cerebrium.dependencies.pip]
torch = "2.2.0"
torchvision = "0.17.0"
torchaudio = "2.2.0"
diffusers = "0.27.2"
transformers = "4.40.2"
accelerate = "0.28.0"
deepCache = "0.1.1"
decord = "0.6.0"
einops = "0.8.0"
omegaconf = "2.3.0"
opencv-python = "4.9.0.80"
mediapipe = "0.10.14"
python_speech_features = "0.6"
librosa = "0.10.1"
scenedetect = "0.6.3"
ffmpeg-python = "0.2.0"
imageio = "2.34.1"
imageio-ffmpeg = "0.4.9"
lpips = "0.1.4"
face-alignment = "1.4.1"
gradio = "4.31.5"
huggingface-hub = "0.22.2"
numpy = "1.26.4"
kornia = "0.7.2"
insightface = "0.7.3"
onnxruntime-gpu = "1.17.1"
requests = "2.31.0"
tqdm = "4.66.2"
pydantic = "2.7.1"
soundfile = "0.12.1"
scipy = "1.11.4"
